name: battlefield-kill-ui publish to store.nanos.world

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Publish package
    steps:
      - uses: actions/checkout@v2
      - name: Nanos Store Action
        uses: nanos-world/nanos-store-action@v1.0
        with:
          # folder which contains the asset/package - if it's on root, leave it blank
          folder: ''
          # name of the asset/package
          name: 'battlefield-kill-ui'
          # changelog of the release - can be edited on the store before it gets published
          changelog: 'built through actions'
          # API token - generate at https://store.nanos.world/settings/tokens/ and set under Settings -> Secrets -> Actions with name STORE_SECRET
          token: ${{ secrets.STORE_SECRET }}